### ISSUE TITLE
app-editors/atom-bin-1.38.1: Build failure dodoc failed No such file or directory: b'copyright'

### ISSUE THREAD

**Issue by simonvanderveldt** [jorgicio/jorgicio-gentoo-overlay#174]
Emerging app-editors/atom-bin-1.38.1 fails with:
```
>>> Install atom-bin-1.38.1 into /var/tmp/portage/app-editors/atom-bin-1.38.1/image/ category app-editors
Traceback (most recent call last):
  File "/usr/lib/portage/python3.6/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.6/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.6/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.6/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.6/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'copyright'
 * ERROR: app-editors/atom-bin-1.38.1::jorgicio failed (install phase):
 *   dodoc failed
```

**Comment by simonvanderveldt** [comment]
Thanks!
