### ISSUE TITLE
x11-misc/cerebro (0.3.0 - 0.3.2) fail to emerge - problem with yarn?

### ISSUE THREAD

**Issue by Mikrotherion** [jorgicio/jorgicio-gentoo-overlay#336]
* cerebro-0.3.0.tar.gz BLAKE2B SHA512 size ;-) ...                      [ ok ]
>>> Unpacking source...
>>> Unpacking cerebro-0.3.0.tar.gz to /var/tmp/portage/x11-misc/cerebro-0.3.0/work
>>> Source unpacked in /var/tmp/portage/x11-misc/cerebro-0.3.0/work
>>> Preparing source in /var/tmp/portage/x11-misc/cerebro-0.3.0/work/cerebro-0.3.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/x11-misc/cerebro-0.3.0/work/cerebro-0.3.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/x11-misc/cerebro-0.3.0/work/cerebro-0.3.0 ...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/auto-launch/-/auto-launch-5.0.1.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com".
info If you think this is a bug, please open a bug report with the information provided in "/var/tmp/portage/x11-misc/cerebro-0.3.0/work/cerebro-0.3.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.17
$ yarn run build-main && yarn run build-renderer && yarn minify
$ cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.electron.js --progress --profile --colors
/bin/sh: line 1: cross-env: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/var/tmp/portage/x11-misc/cerebro-0.3.0/temp/environment: line 1999: node_modules/.bin/build: No such file or directory
>>> Source compiled.
>>> Test phase [not enabled]: x11-misc/cerebro-0.3.0

>>> Install x11-misc/cerebro-0.3.0 into /var/tmp/portage/x11-misc/cerebro-0.3.0/image/
Traceback (most recent call last):
  File "/usr/lib/portage/python3.9/doins.py", line 607, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.9/doins.py", line 596, in main
    if _doins(
  File "/usr/lib/portage/python3.9/doins.py", line 439, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.9/doins.py", line 373, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.9/doins.py", line 181, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'release/linux-unpacked/*'
 * ERROR: x11-misc/cerebro-0.3.0::jorgicio failed (install phase):
 *   doins failed

**Comment by tefiszx** [comment]
I also encountered this problem

> FileNotFoundError: [Errno 2] No such file or directory: b'release/linux-unpacked/*'
 * ERROR: x11-misc/cerebro-0.3.2::jorgicio failed (install phase):
 *   doins failed
 * 
 * If you need support, post the output of `emerge --info '=x11-misc/cerebro-0.3.2::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=x11-misc/cerebro-0.3.2::jorgicio'`.
 * The complete build log is located at '/var/tmp/portage/x11-misc/cerebro-0.3.2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-misc/cerebro-0.3.2/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-misc/cerebro-0.3.2/work/cerebro-0.3.2'
 * S: '/var/tmp/portage/x11-misc/cerebro-0.3.2/work/cerebro-0.3.2'
 * QA Notice: command not found:
 * 
 *      /bin/sh: line 1: cross-env: command not found
